version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - DATABASE_URL=sqlite:///data/formio.db
      - DEBUG=1
    restart: unless-stopped 